### ISSUE TITLE
What do you think is a good name for me?

### ISSUE THREAD

**Issue by de-sh** [jagannathBhat/bhat.dev#1]
ThIs Is JuSt AwEsOmE NOOSE! Did you buy this domain?!!!

**Comment by jagannathBhat** [comment]
Of course, I did. Booked it on the first day it as available. That's why I was able to get this short domain name.

**Comment by de-sh** [comment]
This is just awesome! What are you hosting it on?

**Comment by jagannathBhat** [comment]
It's a GitHub page. I bought bhat.dev from porkbun.com.

**Comment by de-sh** [comment]
I am considering buying a domain for myself too... the current one, i.e. devdutt.me is overdue and I seem to not like the .me domain as much... Give me some suggestions. bhat.dev is just an awesome name that you should stick to forever, like google.com :joy:

**Comment by de-sh** [comment]
shenoi.dev is naive, I don't know... :unamused:

**Comment by jagannathBhat** [comment]
dev.dev?

**Comment by jagannathBhat** [comment]
Nah, it's taken

**Comment by arjunchandran** [comment]
deb.sh ?

**Comment by jagannathBhat** [comment]
dev.sh is not available too

**Comment by jagannathBhat** [comment]
desh.dev?

**Comment by Siddharth1698** [comment]
Jhat.dev sounds better

**Comment by de-sh** [comment]
I hate the fact that BEARly.dev is taken 🙁

**Comment by gex7777** [comment]
How about ladiesman69.dev

**Comment by de-sh** [comment]
> How about ladiesman69.dev

*Replier Classification:* pervert

**Comment by kurianbenoy** [comment]
What's there in a domain name to make it worth of the amount spend? I am still comfortable with .github.io domains :)

**Change my mind**

**Comment by de-sh** [comment]
> What's there in a domain name to make it worth of the amount spend? I am still comfortable with .github.io domains :)
>
> Change my mind

*Deep* 😯 😂
