### ISSUE TITLE
Add Contact and Footer sections

### ISSUE THREAD

**Issue by jagannathBhat** [jagannathBhat/bhat.dev#11]
Sections should look something like the picture below but are consistent with the existing content of the website.
![contact and footer sections](https://user-images.githubusercontent.com/29631578/138587104-e4ef8396-9e03-4dae-bbaf-d3f969c2ff2e.png)

**Comment by ashutosht-01** [comment]
could you please assign this issue to me?

**Comment by hugh-logan** [comment]
I could work on this too @jagannathBhat

**Comment by jagannathBhat** [comment]
I've assigned this to both of you. I'll respond to the earliest proper pull request.
