### ISSUE TITLE
create constant with project info

### ISSUE THREAD

**Issue by jagannathBhat** [jagannathBhat/bhat.dev#15]
create a constant in the following format inside `components/constants.js`. the array should contain data from projects mentioned in #14 . the repos can be in github or gitlab. get the info from the about section of the repos.

![image](https://user-images.githubusercontent.com/29631578/139578647-c324d717-8563-41f4-8f81-4f1659bafb89.png)
_github repo about section_

<br />

![image](https://user-images.githubusercontent.com/29631578/139578657-ca95c578-bdfd-4498-8c1e-6f6db242852c.png)
_gitlab repo about section_

<br />

```js
export const PROJECTS = [
  {
    description: "",
    name: "",
    repoURL: "",
    projectURL: "",
    topics: ["topic 1", "topic 2"],
  },
]
```
_constant format_

**Comment by SurajKumarM98** [comment]
can you assign me this issue please
