### ISSUE TITLE
Increase width of About Section

### ISSUE THREAD

**Issue by jagannathBhat** [jagannathBhat/bhat.dev#2]
The `About` section does not look as desired in larger screens because of the low `max-width`.
![image](https://user-images.githubusercontent.com/29631578/138582563-f875696b-312b-4078-b1bc-4e4af34ab1d1.png)

**Comment by hugh-logan** [comment]
@jagannathBhat Can I work on this?

**Comment by jagannathBhat** [comment]
@hugh-logan please wait. I'm pushing the contribution guide right now. Start once you have read that.

Also, please branch from `astra` because I am currently working on a newer design and the issue is with that design.

**Comment by jagannathBhat** [comment]
Find the contribution guide [here](https://github.com/jagannathBhat/bhat.dev/blob/astra/CONTRIBUTING.md)
