### ISSUE TITLE
UI Issues in Courses section

### ISSUE THREAD

**Issue by jagannathBhat** [jagannathBhat/bhat.dev#3]
- [x] Remove `overflow-x: scroll` from card
- [x] Add `max-width` to card

**Comment by hugh-logan** [comment]
Can I work on this as well @jagannathBhat ?

**Comment by hugh-logan** [comment]
@jagannathBhat What did you mean by `overflow-y: auto`?

**Comment by jagannathBhat** [comment]
That was a mistake on my part. Please get rid of the scroll bar inside the card.
