### ISSUE TITLE
UI changes in Blogs sections

### ISSUE THREAD

**Issue by jagannathBhat** [jagannathBhat/bhat.dev#4]
- [x] Show date and `read post` link on the same line in Blogs section
- [x] Add `max-width` to Blogs section

**Comment by hugh-logan** [comment]
Can I take this one up as well @jagannathBhat ?

**Comment by jagannathBhat** [comment]
@hugh-logan the contribution guide was updated. please make sure to read it.

**Comment by jagannathBhat** [comment]
@hugh-logan please associate the pull request you will create with this issue

**Comment by hugh-logan** [comment]
@jagannathBhat should the `read post` link appear right next to each other or should they have space between them? Please tell me which one to choose from the below.
![image](https://user-images.githubusercontent.com/88522539/138585229-2641bd83-f69f-433d-8082-00b76aaa37a5.png)
![image](https://user-images.githubusercontent.com/88522539/138585457-6032076c-5544-4f6d-bb6d-f9d861ab90b6.png)

**Comment by jagannathBhat** [comment]
Please use the second one.
